spring.datasource.url=jdbc:postgresql://localhost:5432/do_your_home_work_bot
spring.datasource.username=postgres
spring.datasource.password=postgres
telegram.bot.token=7851993248:AAEJkQwLlHggHAWROli-WSrP4-MXeQDHFKI

spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml


